version: '3'
services:
  backend:
    build: .
    ports:
      - 3001:3001
    depends_on:
      - redis
    networks:
      - backendbank

  mariadb:
    image: mariadb:latest
    volumes:
      - ~/.backendrent/data/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      TZ: Asia/Bangkok
      MYSQL_ROOT_PASSWORD: mysql_root_password
    networks:
      - backendbank

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - backendbank

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: mysql_root_password
      UPLOAD_LIMIT: 1G
    ports:
      - 8080:80
    depends_on:
      - mariadb
    networks:
      - backendbank

networks:
  backendbank:
    external: true
