version: '3'
networks:
    backendbank:
        driver: bridge
volumes:
    mariadb:
        driver: local
    phpmyadmin:
        driver: local
services:
  backend:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 3001:3001
    networks:
      - backendbank
    depends_on:
      - redis

  mariadb:
    image: mariadb:latest
    container_name: mariadb_backend
    volumes:
      - ~/.backendrent/data/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment: 
      TZ: Asia/Bangkok
      MYSQL_ROOT_PASSWORD: mysql_root_password
    networks:
      - backendbank

  redis:
    image: redis
    container_name: redis-backend
    ports:
      - 6379:6379
    restart: always
    networks:
      - backendbank

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_backend_rent_home
    restart: always
    environment:
        PMA_ARBITRARY: 1
        PMA_HOST: mariadb
        MYSQL_ROOT_PASSWORD: mysql_root_password
        UPLOAD_LIMIT: 1G
    ports:
        - 8080:80
    depends_on:
        - mariadb
    networks:
        - backendbank